### ISSUE TITLE
THIS IS NOT OKAY

### ISSUE THREAD

**Issue by soquerosaberderoblox** [ThePotato97/RoSearcher#17]
i was looking in twitter and found one issue reported by a corp called roblox and they said the extison is not safe and trustable so i trutsed it and after testing i got banned pls fix this now

**Comment by ThePotato97** [comment]
You got banned for using this extension?

**Comment by soquerosaberderoblox** [comment]
Yup

Em seg, 8 de ago de 2022 18:56, ThePotato ***@***.***>
escreveu:
