### ISSUE TITLE
bruh people think u added a virus

### ISSUE THREAD

**Issue by 7ih** [ThePotato97/RoSearcher#18]
:|

**Comment by wilsontulus** [comment]
This is due to the Chrome webstore version being taken down, people made a malicious version of it in CWS.
Since the Firefox version is still up, no problems for Firefox users out there 😎

**Comment by GamerGirl92** [comment]
This is the legit one though right?

**Comment by ThePotato97** [comment]
> This is the legit one though right?

https://chrome.google.com/webstore/detail/rosearcher/kogoeldkgknjbdajddjjfijggnpcffib

https://addons.mozilla.org/en-US/firefox/addon/rosearcher/
