### ISSUE TITLE
Making clicking on any ad on Roblox, redirect to the same random game

### ISSUE THREAD

**Issue by MatadorProBr** [ThePotato97/RoSearcher#23]
On https://github.com/ThePotato97/RoSearcher/pull/19 (to be more specify, https://github.com/ThePotato97/RoSearcher/blob/31d20d48e760a65eba4ea8180bfdce9d7e69d925/rosearch-chrome-edge/js/plugin.js) @ThePotato97, the creator of this fork added a code that if you check, it has a gist with the **test.json** name (that is deleted) and some code that redirects all ads that you click on Roblox to a game that for now we don't know, after some time it got removed on #20 (to be more specify, https://github.com/ThePotato97/RoSearcher/blob/e92ebc55fa94d64e94cfc640310b6ddfafe6c9b2/rosearch-chrome-edge/js/plugin.js).

With this I wanted to ask, why this was added? You are trying to make some money making partnership with games and promoting in a very strange way without the user even knowing?

(If they try to delete the commit history using git, it's all saved on [Wayback Machine](https://web.archive.org/web/20220809213228/https://github.com/ThePotato97/RoSearcher/commits/master) so you can see it even if they delete it)

**Comment by ThePotato97** [comment]
do you think I published the commits on accident and made a pull request?

**Comment by MatadorProBr** [comment]
> do you think I published the commits on accident and made a pull request?

no?

**Comment by ThePotato97** [comment]
It was just funny redirecting all ads to a few random games, no money involved.
