### ISSUE TITLE
Is This The Legit RoSearcher?

### ISSUE THREAD

**Issue by GamerGirl92** [ThePotato97/RoSearcher#24]
I have seen there were lots of people saying that people made fake rosearchers which hack you so is this the real one? #

**Comment by Neo802** [comment]
I think it is the legit RoSearcher, since it is on Github. Try to look into the code too, that's how you can determine whether it is the real one or not.

**Comment by GamerGirl92** [comment]
Ok thnx

**Comment by Steefuno** [comment]
idk if it's malicious or not, but it's forking another Rosearcher, so this one wouldnt be a real one

**Comment by xxa1234uetrredhdfnzb** [comment]
PLEASE, if this is not real. THEN HOW TO GET RID OF IT?! I don't want to lose an account with a LOT OF PUMPING!

**Comment by terminite1** [comment]
i checked through every file seems legit for now

**Comment by Steefuno** [comment]
comparing it to the forked repo, so far, I think it's just the microsoft edge and opera version

**Comment by halreonHD** [comment]
so is this safe or not?

**Comment by Steefuno** [comment]
seems safe to me
I don't have anything to confirm it's safe though
