### ISSUE TITLE
This is A warning.

### ISSUE THREAD

**Issue by GefenWasHere** [ThePotato97/RoSearcher#26]
You have 2 weeks.
**_#SlayersAssistant_**

**Comment by GefenWasHere** [comment]
They are hacking people, We are warning all of you, to DELETE THE EXTENSION.

**Comment by DiamondBroPlayz** [comment]
lol this is open-source. you just watched a commentary and thought you were cool

**Comment by BEASTover9000** [comment]
cry more :3
