### ISSUE TITLE
RoSearcher Not Working.

### ISSUE THREAD

**Issue by cozykj** [ThePotato97/RoSearcher#33]
Okay so the little ui shows up, "Username" Search, and Itll say found user or user not found. 
But it will now show what server they in, all it says is UserFound.

Can you help me?

**Comment by latonnas** [comment]
this happens to me too and it just adds like a big blank on top of the server list help plsssssssssssssssss

**Comment by Komas19-new** [comment]
it was fixed by roblox months ago

**Comment by latonnas** [comment]
no it still happens

**Comment by Komas19-new** [comment]
i meant that roblox patched rosearcher and all extensions like that
