### ISSUE TITLE
information about the rosearcher exstension

### ISSUE THREAD

**Issue by alexander15674** [ThePotato97/RoSearcher#35]
Why the search button doesn't work?

**Comment by kripodobniy** [comment]
+, don't work

**Comment by alexander15674** [comment]
Hi, can you please fix the button or search? A thousand thanks

Il mar 11 apr 2023, 14:33 Alexander ***@***.***> ha scritto:

**Comment by alexander15674** [comment]
will be resolved?

**Comment by Fjmf1sh** [comment]
is it still a virus
