### ISSUE TITLE
searching fix

### ISSUE THREAD

**Issue by DraidS** [ThePotato97/RoSearcher#38]
please update searching to the new roblox api

from this api.roblox.com to users.roblox.com (you have to send a post request now https://users.roblox.com/docs/index.html) 

    let endpoint;
    if (/^\d+$/.test(this.input.value)) {
      endpoint = `api.roblox.com/users/${this.input.value}`;
    } else {
      endpoint = `api.roblox.com/users/get-by-username?username=${this.input.value}`;
    }
    const user = await get(endpoint);
    
    heres the new links 
    
    users.roblox.com/v1/users
    and
    users.roblox.com/v1/usernames/users

**Comment by ghost** [comment]
you can try to make a pull request

**Comment by ic3dlem0n** [comment]
how can i fix it myself i need this

**Comment by gustwindy** [comment]
bump.
