### ISSUE TITLE
i can't put the extencion on te toolbar 

### ISSUE THREAD

**Issue by YOSHO-SS** [ThePotato97/RoSearcher#8]
Hello! I would like to report an error that I do not know if it is from the extension itself, from firefox or even mine, but in any case I report it.

These days I installed and uninstalled the extension because the bar did not appear on the servers, but when I did that the extension did not return to the toolbar and I cannot find a way to place it

**Comment by ThePotato97** [comment]
The extension is embedded not on the toolbar
